export const AUTHENTICATE = "AUTHENTICATE";
export const REMOVE_WHOLE_CART_DATA = "REMOVE_WHOLE_CART_DATA";
export const ADD_WHOLE_CART = 'ADD_WHOLE_CART';
export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const ADD_DATA = 'ADD_DATA';
export const ADD_SAME_CART_ITEM = 'ADD_SAME_CART_ITEM';
export const REMOVE_SAME_CART_ITEM = 'REMOVE_SAME_CART_ITEM';
export const REMOVE_WHOLE_ITEM_FROM_CART = 'REMOVE_WHOLE_ITEM_FROM_CART';
export const ADD_PRICE = 'ADD_PRICE';
export const REMOVE_PRICE = 'REMOVE_PRICE';
export const ADD_QUANTITY_FROM_SELECTED_ITEM = "ADD_QUANTITY_FROM_SELECTED_ITEM";

export const ADD_FROM_SHOP = "ADD_FROM_SHOP";
export const SET_USER_DATA = "SET_USER_DATA";
export const DELETE_ALL_FROM_CART = "DELETE_ALL_FROM_CART";
